#SPDX-License-Identifier: MIT @Copyright 2025 yet.another.artem
---
# tasks file for ansible_deploy_tg_application_role
- name: Install Docker on remote system
  ansible.builtin.include_role:
    name: "xiaoyao9184.docker"
- name: Pull Docker image
  community.docker.docker_image:
    name: "ananotherartem/chasovoy-tg-bot:latest"
    source: "pull"
- name: Run Docker container
  community.docker.docker_container:
    name: "chasovoy-tg-bot"
    image: "ananotherartem/chasovoy-tg-bot:latest"
    env: "{{ env_vars }}"
    volumes: "{{ item }}"
  loop: "{{ volumes }}"
